import type { BoardSquare } from "../types/game";

export const BOARD_SQUARES: BoardSquare[] = [
  // Bottom row (right to left): 0-10
  { index: 0, name: "GO", kind: "go", price: null, colorGroup: null, rent: [] },
  {
    index: 1,
    name: "Mediterranean Ave",
    kind: "property",
    price: 60,
    colorGroup: "brown",
    rent: [2, 10, 30, 90, 160, 250],
  },
  {
    index: 2,
    name: "Community Chest",
    kind: "community-chest",
    price: null,
    colorGroup: null,
    rent: [],
  },
  {
    index: 3,
    name: "Baltic Ave",
    kind: "property",
    price: 60,
    colorGroup: "brown",
    rent: [4, 20, 60, 180, 320, 450],
  },
  {
    index: 4,
    name: "Income Tax",
    kind: "tax",
    price: null,
    colorGroup: null,
    rent: [],
  },
  {
    index: 5,
    name: "Reading Railroad",
    kind: "railroad",
    price: 200,
    colorGroup: null,
    rent: [25, 50, 100, 200],
  },
  {
    index: 6,
    name: "Oriental Ave",
    kind: "property",
    price: 100,
    colorGroup: "light-blue",
    rent: [6, 30, 90, 270, 400, 550],
  },
  {
    index: 7,
    name: "Chance",
    kind: "chance",
    price: null,
    colorGroup: null,
    rent: [],
  },
  {
    index: 8,
    name: "Vermont Ave",
    kind: "property",
    price: 100,
    colorGroup: "light-blue",
    rent: [6, 30, 90, 270, 400, 550],
  },
  {
    index: 9,
    name: "Connecticut Ave",
    kind: "property",
    price: 120,
    colorGroup: "light-blue",
    rent: [8, 40, 100, 300, 450, 600],
  },
  // Jail (corner)
  {
    index: 10,
    name: "Jail / Just Visiting",
    kind: "jail",
    price: null,
    colorGroup: null,
    rent: [],
  },
  // Left column (bottom to top): 11-19
  {
    index: 11,
    name: "St. Charles Place",
    kind: "property",
    price: 140,
    colorGroup: "pink",
    rent: [10, 50, 150, 450, 625, 750],
  },
  {
    index: 12,
    name: "Electric Company",
    kind: "utility",
    price: 150,
    colorGroup: null,
    rent: [],
  },
  {
    index: 13,
    name: "States Ave",
    kind: "property",
    price: 140,
    colorGroup: "pink",
    rent: [10, 50, 150, 450, 625, 750],
  },
  {
    index: 14,
    name: "Virginia Ave",
    kind: "property",
    price: 160,
    colorGroup: "pink",
    rent: [12, 60, 180, 500, 700, 900],
  },
  {
    index: 15,
    name: "Pennsylvania Railroad",
    kind: "railroad",
    price: 200,
    colorGroup: null,
    rent: [25, 50, 100, 200],
  },
  {
    index: 16,
    name: "St. James Place",
    kind: "property",
    price: 180,
    colorGroup: "orange",
    rent: [14, 70, 200, 550, 750, 950],
  },
  {
    index: 17,
    name: "Community Chest",
    kind: "community-chest",
    price: null,
    colorGroup: null,
    rent: [],
  },
  {
    index: 18,
    name: "Tennessee Ave",
    kind: "property",
    price: 180,
    colorGroup: "orange",
    rent: [14, 70, 200, 550, 750, 950],
  },
  {
    index: 19,
    name: "New York Ave",
    kind: "property",
    price: 200,
    colorGroup: "orange",
    rent: [16, 80, 220, 600, 800, 1000],
  },
  // Free Parking (corner)
  {
    index: 20,
    name: "Free Parking",
    kind: "free-parking",
    price: null,
    colorGroup: null,
    rent: [],
  },
  // Top row (left to right): 21-29
  {
    index: 21,
    name: "Kentucky Ave",
    kind: "property",
    price: 220,
    colorGroup: "red",
    rent: [18, 90, 250, 700, 875, 1050],
  },
  {
    index: 22,
    name: "Chance",
    kind: "chance",
    price: null,
    colorGroup: null,
    rent: [],
  },
  {
    index: 23,
    name: "Indiana Ave",
    kind: "property",
    price: 220,
    colorGroup: "red",
    rent: [18, 90, 250, 700, 875, 1050],
  },
  {
    index: 24,
    name: "Illinois Ave",
    kind: "property",
    price: 240,
    colorGroup: "red",
    rent: [20, 100, 300, 750, 925, 1100],
  },
  {
    index: 25,
    name: "B&O Railroad",
    kind: "railroad",
    price: 200,
    colorGroup: null,
    rent: [25, 50, 100, 200],
  },
  {
    index: 26,
    name: "Atlantic Ave",
    kind: "property",
    price: 260,
    colorGroup: "yellow",
    rent: [22, 110, 330, 800, 975, 1150],
  },
  {
    index: 27,
    name: "Ventnor Ave",
    kind: "property",
    price: 260,
    colorGroup: "yellow",
    rent: [22, 110, 330, 800, 975, 1150],
  },
  {
    index: 28,
    name: "Water Works",
    kind: "utility",
    price: 150,
    colorGroup: null,
    rent: [],
  },
  {
    index: 29,
    name: "Marvin Gardens",
    kind: "property",
    price: 280,
    colorGroup: "yellow",
    rent: [24, 120, 360, 850, 1025, 1200],
  },
  // Go To Jail (corner)
  {
    index: 30,
    name: "Go To Jail",
    kind: "go-to-jail",
    price: null,
    colorGroup: null,
    rent: [],
  },
  // Right column (top to bottom): 31-39
  {
    index: 31,
    name: "Pacific Ave",
    kind: "property",
    price: 300,
    colorGroup: "green",
    rent: [26, 130, 390, 900, 1100, 1275],
  },
  {
    index: 32,
    name: "North Carolina Ave",
    kind: "property",
    price: 300,
    colorGroup: "green",
    rent: [26, 130, 390, 900, 1100, 1275],
  },
  {
    index: 33,
    name: "Community Chest",
    kind: "community-chest",
    price: null,
    colorGroup: null,
    rent: [],
  },
  {
    index: 34,
    name: "Pennsylvania Ave",
    kind: "property",
    price: 320,
    colorGroup: "green",
    rent: [28, 150, 450, 1000, 1200, 1400],
  },
  {
    index: 35,
    name: "Short Line Railroad",
    kind: "railroad",
    price: 200,
    colorGroup: null,
    rent: [25, 50, 100, 200],
  },
  {
    index: 36,
    name: "Chance",
    kind: "chance",
    price: null,
    colorGroup: null,
    rent: [],
  },
  {
    index: 37,
    name: "Park Place",
    kind: "property",
    price: 350,
    colorGroup: "dark-blue",
    rent: [35, 175, 500, 1100, 1300, 1500],
  },
  {
    index: 38,
    name: "Luxury Tax",
    kind: "tax",
    price: null,
    colorGroup: null,
    rent: [],
  },
  {
    index: 39,
    name: "Boardwalk",
    kind: "property",
    price: 400,
    colorGroup: "dark-blue",
    rent: [50, 200, 600, 1400, 1700, 2000],
  },
];

export const COLOR_GROUP_HEX: Record<string, string> = {
  brown: "#8B5E3C",
  "light-blue": "#AAD9F0",
  pink: "#E87FB0",
  orange: "#F5A623",
  red: "#E13C3C",
  yellow: "#F5E642",
  green: "#2ECC71",
  "dark-blue": "#2C3E96",
};

export const STAKE_PRESETS = [10, 25, 50, 100, 250, 500];
