/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BuyPropertyResult = { 'Ok' : GameView } |
  { 'Err' : string };
export interface CreateGameArgs {
  'stakeAmount' : bigint,
  'currency' : Currency,
}
export type Currency = { 'ICP' : null } |
  { 'ckBTC' : null };
export type EventKind = { 'PlayerJoined' : { 'player' : UserId } } |
  { 'GameWon' : { 'winner' : UserId } } |
  { 'Bankrupt' : null } |
  { 'Moved' : { 'to' : bigint, 'from' : bigint } } |
  { 'SentToJail' : null } |
  { 'RentPaid' : { 'to' : UserId, 'from' : UserId, 'amount' : bigint } } |
  { 'TaxPaid' : { 'amount' : bigint } } |
  { 'PropertyBought' : { 'square' : bigint, 'price' : bigint } } |
  { 'Rolled' : { 'die1' : bigint, 'die2' : bigint } } |
  { 'GameStarted' : null };
export interface GameEvent {
  'player' : UserId,
  'kind' : EventKind,
  'timestamp' : Timestamp,
}
export type GameId = string;
export type GamePhase = { 'Lobby' : null } |
  { 'Playing' : null } |
  { 'Finished' : null };
export interface GameView {
  'id' : GameId,
  'pendingBuySquare' : [] | [bigint],
  'host' : UserId,
  'stakeAmount' : bigint,
  'properties' : Array<PropertyOwnership>,
  'players' : Array<PlayerView>,
  'turnIndex' : bigint,
  'events' : Array<GameEvent>,
  'currency' : Currency,
  'phase' : GamePhase,
  'escrowLocked' : boolean,
}
export type JoinGameResult = { 'Ok' : GameView } |
  { 'Err' : string };
export interface PlayerView {
  'id' : UserId,
  'isBankrupt' : boolean,
  'cash' : bigint,
  'inJail' : boolean,
  'isReady' : boolean,
  'position' : bigint,
}
export interface PropertyOwnership { 'owner' : UserId, 'square' : bigint }
export type RollResult = {
    'Ok' : {
      'die1' : bigint,
      'die2' : bigint,
      'event' : string,
      'newPosition' : bigint,
    }
  } |
  { 'Err' : string };
export type Timestamp = bigint;
export type UserId = Principal;
export interface _SERVICE {
  'buyProperty' : ActorMethod<[GameId], BuyPropertyResult>,
  'createGame' : ActorMethod<[CreateGameArgs], GameView>,
  'getEvents' : ActorMethod<[GameId, bigint], Array<GameEvent>>,
  'getGame' : ActorMethod<[GameId], [] | [GameView]>,
  'getOrCreatePlayer' : ActorMethod<[], PlayerView>,
  'getPlayer' : ActorMethod<[UserId], [] | [PlayerView]>,
  'joinGame' : ActorMethod<[GameId], JoinGameResult>,
  'listOpenGames' : ActorMethod<[], Array<GameView>>,
  'passProperty' : ActorMethod<[GameId], JoinGameResult>,
  'rollDice' : ActorMethod<[GameId], RollResult>,
  'setReady' : ActorMethod<[GameId], JoinGameResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];