/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GameId = IDL.Text;
export const UserId = IDL.Principal;
export const PropertyOwnership = IDL.Record({
  'owner' : UserId,
  'square' : IDL.Nat,
});
export const PlayerView = IDL.Record({
  'id' : UserId,
  'isBankrupt' : IDL.Bool,
  'cash' : IDL.Nat,
  'inJail' : IDL.Bool,
  'isReady' : IDL.Bool,
  'position' : IDL.Nat,
});
export const EventKind = IDL.Variant({
  'PlayerJoined' : IDL.Record({ 'player' : UserId }),
  'GameWon' : IDL.Record({ 'winner' : UserId }),
  'Bankrupt' : IDL.Null,
  'Moved' : IDL.Record({ 'to' : IDL.Nat, 'from' : IDL.Nat }),
  'SentToJail' : IDL.Null,
  'RentPaid' : IDL.Record({
    'to' : UserId,
    'from' : UserId,
    'amount' : IDL.Nat,
  }),
  'TaxPaid' : IDL.Record({ 'amount' : IDL.Nat }),
  'PropertyBought' : IDL.Record({ 'square' : IDL.Nat, 'price' : IDL.Nat }),
  'Rolled' : IDL.Record({ 'die1' : IDL.Nat, 'die2' : IDL.Nat }),
  'GameStarted' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const GameEvent = IDL.Record({
  'player' : UserId,
  'kind' : EventKind,
  'timestamp' : Timestamp,
});
export const Currency = IDL.Variant({ 'ICP' : IDL.Null, 'ckBTC' : IDL.Null });
export const GamePhase = IDL.Variant({
  'Lobby' : IDL.Null,
  'Playing' : IDL.Null,
  'Finished' : IDL.Null,
});
export const GameView = IDL.Record({
  'id' : GameId,
  'pendingBuySquare' : IDL.Opt(IDL.Nat),
  'host' : UserId,
  'stakeAmount' : IDL.Nat,
  'properties' : IDL.Vec(PropertyOwnership),
  'players' : IDL.Vec(PlayerView),
  'turnIndex' : IDL.Nat,
  'events' : IDL.Vec(GameEvent),
  'currency' : Currency,
  'phase' : GamePhase,
  'escrowLocked' : IDL.Bool,
});
export const BuyPropertyResult = IDL.Variant({
  'Ok' : GameView,
  'Err' : IDL.Text,
});
export const CreateGameArgs = IDL.Record({
  'stakeAmount' : IDL.Nat,
  'currency' : Currency,
});
export const JoinGameResult = IDL.Variant({
  'Ok' : GameView,
  'Err' : IDL.Text,
});
export const RollResult = IDL.Variant({
  'Ok' : IDL.Record({
    'die1' : IDL.Nat,
    'die2' : IDL.Nat,
    'event' : IDL.Text,
    'newPosition' : IDL.Nat,
  }),
  'Err' : IDL.Text,
});

export const idlService = IDL.Service({
  'buyProperty' : IDL.Func([GameId], [BuyPropertyResult], []),
  'createGame' : IDL.Func([CreateGameArgs], [GameView], []),
  'getEvents' : IDL.Func([GameId, IDL.Nat], [IDL.Vec(GameEvent)], ['query']),
  'getGame' : IDL.Func([GameId], [IDL.Opt(GameView)], ['query']),
  'getOrCreatePlayer' : IDL.Func([], [PlayerView], []),
  'getPlayer' : IDL.Func([UserId], [IDL.Opt(PlayerView)], ['query']),
  'joinGame' : IDL.Func([GameId], [JoinGameResult], []),
  'listOpenGames' : IDL.Func([], [IDL.Vec(GameView)], ['query']),
  'passProperty' : IDL.Func([GameId], [JoinGameResult], []),
  'rollDice' : IDL.Func([GameId], [RollResult], []),
  'setReady' : IDL.Func([GameId], [JoinGameResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GameId = IDL.Text;
  const UserId = IDL.Principal;
  const PropertyOwnership = IDL.Record({
    'owner' : UserId,
    'square' : IDL.Nat,
  });
  const PlayerView = IDL.Record({
    'id' : UserId,
    'isBankrupt' : IDL.Bool,
    'cash' : IDL.Nat,
    'inJail' : IDL.Bool,
    'isReady' : IDL.Bool,
    'position' : IDL.Nat,
  });
  const EventKind = IDL.Variant({
    'PlayerJoined' : IDL.Record({ 'player' : UserId }),
    'GameWon' : IDL.Record({ 'winner' : UserId }),
    'Bankrupt' : IDL.Null,
    'Moved' : IDL.Record({ 'to' : IDL.Nat, 'from' : IDL.Nat }),
    'SentToJail' : IDL.Null,
    'RentPaid' : IDL.Record({
      'to' : UserId,
      'from' : UserId,
      'amount' : IDL.Nat,
    }),
    'TaxPaid' : IDL.Record({ 'amount' : IDL.Nat }),
    'PropertyBought' : IDL.Record({ 'square' : IDL.Nat, 'price' : IDL.Nat }),
    'Rolled' : IDL.Record({ 'die1' : IDL.Nat, 'die2' : IDL.Nat }),
    'GameStarted' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const GameEvent = IDL.Record({
    'player' : UserId,
    'kind' : EventKind,
    'timestamp' : Timestamp,
  });
  const Currency = IDL.Variant({ 'ICP' : IDL.Null, 'ckBTC' : IDL.Null });
  const GamePhase = IDL.Variant({
    'Lobby' : IDL.Null,
    'Playing' : IDL.Null,
    'Finished' : IDL.Null,
  });
  const GameView = IDL.Record({
    'id' : GameId,
    'pendingBuySquare' : IDL.Opt(IDL.Nat),
    'host' : UserId,
    'stakeAmount' : IDL.Nat,
    'properties' : IDL.Vec(PropertyOwnership),
    'players' : IDL.Vec(PlayerView),
    'turnIndex' : IDL.Nat,
    'events' : IDL.Vec(GameEvent),
    'currency' : Currency,
    'phase' : GamePhase,
    'escrowLocked' : IDL.Bool,
  });
  const BuyPropertyResult = IDL.Variant({ 'Ok' : GameView, 'Err' : IDL.Text });
  const CreateGameArgs = IDL.Record({
    'stakeAmount' : IDL.Nat,
    'currency' : Currency,
  });
  const JoinGameResult = IDL.Variant({ 'Ok' : GameView, 'Err' : IDL.Text });
  const RollResult = IDL.Variant({
    'Ok' : IDL.Record({
      'die1' : IDL.Nat,
      'die2' : IDL.Nat,
      'event' : IDL.Text,
      'newPosition' : IDL.Nat,
    }),
    'Err' : IDL.Text,
  });
  
  return IDL.Service({
    'buyProperty' : IDL.Func([GameId], [BuyPropertyResult], []),
    'createGame' : IDL.Func([CreateGameArgs], [GameView], []),
    'getEvents' : IDL.Func([GameId, IDL.Nat], [IDL.Vec(GameEvent)], ['query']),
    'getGame' : IDL.Func([GameId], [IDL.Opt(GameView)], ['query']),
    'getOrCreatePlayer' : IDL.Func([], [PlayerView], []),
    'getPlayer' : IDL.Func([UserId], [IDL.Opt(PlayerView)], ['query']),
    'joinGame' : IDL.Func([GameId], [JoinGameResult], []),
    'listOpenGames' : IDL.Func([], [IDL.Vec(GameView)], ['query']),
    'passProperty' : IDL.Func([GameId], [JoinGameResult], []),
    'rollDice' : IDL.Func([GameId], [RollResult], []),
    'setReady' : IDL.Func([GameId], [JoinGameResult], []),
  });
};

export const init = ({ IDL }) => { return []; };