/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface GameView {
    id: GameId;
    pendingBuySquare?: bigint;
    host: UserId;
    stakeAmount: bigint;
    properties: Array<PropertyOwnership>;
    players: Array<PlayerView>;
    turnIndex: bigint;
    events: Array<GameEvent>;
    currency: Currency;
    phase: GamePhase;
    escrowLocked: boolean;
}
export interface PropertyOwnership {
    owner: UserId;
    square: bigint;
}
export type JoinGameResult = {
    __kind__: "Ok";
    Ok: GameView;
} | {
    __kind__: "Err";
    Err: string;
};
export type EventKind = {
    __kind__: "PlayerJoined";
    PlayerJoined: {
        player: UserId;
    };
} | {
    __kind__: "GameWon";
    GameWon: {
        winner: UserId;
    };
} | {
    __kind__: "Bankrupt";
    Bankrupt: null;
} | {
    __kind__: "Moved";
    Moved: {
        to: bigint;
        from: bigint;
    };
} | {
    __kind__: "SentToJail";
    SentToJail: null;
} | {
    __kind__: "RentPaid";
    RentPaid: {
        to: UserId;
        from: UserId;
        amount: bigint;
    };
} | {
    __kind__: "TaxPaid";
    TaxPaid: {
        amount: bigint;
    };
} | {
    __kind__: "PropertyBought";
    PropertyBought: {
        square: bigint;
        price: bigint;
    };
} | {
    __kind__: "Rolled";
    Rolled: {
        die1: bigint;
        die2: bigint;
    };
} | {
    __kind__: "GameStarted";
    GameStarted: null;
};
export type BuyPropertyResult = {
    __kind__: "Ok";
    Ok: GameView;
} | {
    __kind__: "Err";
    Err: string;
};
export type UserId = Principal;
export type RollResult = {
    __kind__: "Ok";
    Ok: {
        die1: bigint;
        die2: bigint;
        event: string;
        newPosition: bigint;
    };
} | {
    __kind__: "Err";
    Err: string;
};
export type GameId = string;
export interface GameEvent {
    player: UserId;
    kind: EventKind;
    timestamp: Timestamp;
}
export interface CreateGameArgs {
    stakeAmount: bigint;
    currency: Currency;
}
export interface PlayerView {
    id: UserId;
    isBankrupt: boolean;
    cash: bigint;
    inJail: boolean;
    isReady: boolean;
    position: bigint;
}
export enum Currency {
    ICP = "ICP",
    ckBTC = "ckBTC"
}
export enum GamePhase {
    Lobby = "Lobby",
    Playing = "Playing",
    Finished = "Finished"
}
export interface backendInterface {
    buyProperty(gameId: GameId): Promise<BuyPropertyResult>;
    createGame(args: CreateGameArgs): Promise<GameView>;
    getEvents(gameId: GameId, limit: bigint): Promise<Array<GameEvent>>;
    getGame(gameId: GameId): Promise<GameView | null>;
    getOrCreatePlayer(): Promise<PlayerView>;
    getPlayer(playerId: UserId): Promise<PlayerView | null>;
    joinGame(gameId: GameId): Promise<JoinGameResult>;
    listOpenGames(): Promise<Array<GameView>>;
    passProperty(gameId: GameId): Promise<JoinGameResult>;
    rollDice(gameId: GameId): Promise<RollResult>;
    setReady(gameId: GameId): Promise<JoinGameResult>;
}
import type { BuyPropertyResult as _BuyPropertyResult, CreateGameArgs as _CreateGameArgs, Currency as _Currency, EventKind as _EventKind, GameEvent as _GameEvent, GameId as _GameId, GamePhase as _GamePhase, GameView as _GameView, JoinGameResult as _JoinGameResult, PlayerView as _PlayerView, PropertyOwnership as _PropertyOwnership, RollResult as _RollResult, Timestamp as _Timestamp, UserId as _UserId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async buyProperty(arg0: GameId): Promise<BuyPropertyResult> {
        if (this.processError) {
            try {
                const result = await this.actor.buyProperty(arg0);
                return from_candid_BuyPropertyResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.buyProperty(arg0);
            return from_candid_BuyPropertyResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createGame(arg0: CreateGameArgs): Promise<GameView> {
        if (this.processError) {
            try {
                const result = await this.actor.createGame(to_candid_CreateGameArgs_n15(this._uploadFile, this._downloadFile, arg0));
                return from_candid_GameView_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGame(to_candid_CreateGameArgs_n15(this._uploadFile, this._downloadFile, arg0));
            return from_candid_GameView_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEvents(arg0: GameId, arg1: bigint): Promise<Array<GameEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvents(arg0, arg1);
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvents(arg0, arg1);
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGame(arg0: GameId): Promise<GameView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGame(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGame(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrCreatePlayer(): Promise<PlayerView> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrCreatePlayer();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrCreatePlayer();
            return result;
        }
    }
    async getPlayer(arg0: UserId): Promise<PlayerView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayer(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayer(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async joinGame(arg0: GameId): Promise<JoinGameResult> {
        if (this.processError) {
            try {
                const result = await this.actor.joinGame(arg0);
                return from_candid_JoinGameResult_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinGame(arg0);
            return from_candid_JoinGameResult_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async listOpenGames(): Promise<Array<GameView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listOpenGames();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listOpenGames();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async passProperty(arg0: GameId): Promise<JoinGameResult> {
        if (this.processError) {
            try {
                const result = await this.actor.passProperty(arg0);
                return from_candid_JoinGameResult_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.passProperty(arg0);
            return from_candid_JoinGameResult_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async rollDice(arg0: GameId): Promise<RollResult> {
        if (this.processError) {
            try {
                const result = await this.actor.rollDice(arg0);
                return from_candid_RollResult_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rollDice(arg0);
            return from_candid_RollResult_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async setReady(arg0: GameId): Promise<JoinGameResult> {
        if (this.processError) {
            try {
                const result = await this.actor.setReady(arg0);
                return from_candid_JoinGameResult_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setReady(arg0);
            return from_candid_JoinGameResult_n21(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BuyPropertyResult_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BuyPropertyResult): BuyPropertyResult {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Currency_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Currency): Currency {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_EventKind_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EventKind): EventKind {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_GameEvent_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameEvent): GameEvent {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_GamePhase_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GamePhase): GamePhase {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_GameView_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameView): GameView {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_JoinGameResult_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JoinGameResult): JoinGameResult {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_RollResult_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RollResult): RollResult {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GameView]): GameView | null {
    return value.length === 0 ? null : from_candid_GameView_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlayerView]): PlayerView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _GameId;
    pendingBuySquare: [] | [bigint];
    host: _UserId;
    stakeAmount: bigint;
    properties: Array<_PropertyOwnership>;
    players: Array<_PlayerView>;
    turnIndex: bigint;
    events: Array<_GameEvent>;
    currency: _Currency;
    phase: _GamePhase;
    escrowLocked: boolean;
}): {
    id: GameId;
    pendingBuySquare?: bigint;
    host: UserId;
    stakeAmount: bigint;
    properties: Array<PropertyOwnership>;
    players: Array<PlayerView>;
    turnIndex: bigint;
    events: Array<GameEvent>;
    currency: Currency;
    phase: GamePhase;
    escrowLocked: boolean;
} {
    return {
        id: value.id,
        pendingBuySquare: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.pendingBuySquare)),
        host: value.host,
        stakeAmount: value.stakeAmount,
        properties: value.properties,
        players: value.players,
        turnIndex: value.turnIndex,
        events: from_candid_vec_n6(_uploadFile, _downloadFile, value.events),
        currency: from_candid_Currency_n11(_uploadFile, _downloadFile, value.currency),
        phase: from_candid_GamePhase_n13(_uploadFile, _downloadFile, value.phase),
        escrowLocked: value.escrowLocked
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    player: _UserId;
    kind: _EventKind;
    timestamp: _Timestamp;
}): {
    player: UserId;
    kind: EventKind;
    timestamp: Timestamp;
} {
    return {
        player: value.player,
        kind: from_candid_EventKind_n9(_uploadFile, _downloadFile, value.kind),
        timestamp: value.timestamp
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    PlayerJoined: {
        player: _UserId;
    };
} | {
    GameWon: {
        winner: _UserId;
    };
} | {
    Bankrupt: null;
} | {
    Moved: {
        to: bigint;
        from: bigint;
    };
} | {
    SentToJail: null;
} | {
    RentPaid: {
        to: _UserId;
        from: _UserId;
        amount: bigint;
    };
} | {
    TaxPaid: {
        amount: bigint;
    };
} | {
    PropertyBought: {
        square: bigint;
        price: bigint;
    };
} | {
    Rolled: {
        die1: bigint;
        die2: bigint;
    };
} | {
    GameStarted: null;
}): {
    __kind__: "PlayerJoined";
    PlayerJoined: {
        player: UserId;
    };
} | {
    __kind__: "GameWon";
    GameWon: {
        winner: UserId;
    };
} | {
    __kind__: "Bankrupt";
    Bankrupt: null;
} | {
    __kind__: "Moved";
    Moved: {
        to: bigint;
        from: bigint;
    };
} | {
    __kind__: "SentToJail";
    SentToJail: null;
} | {
    __kind__: "RentPaid";
    RentPaid: {
        to: UserId;
        from: UserId;
        amount: bigint;
    };
} | {
    __kind__: "TaxPaid";
    TaxPaid: {
        amount: bigint;
    };
} | {
    __kind__: "PropertyBought";
    PropertyBought: {
        square: bigint;
        price: bigint;
    };
} | {
    __kind__: "Rolled";
    Rolled: {
        die1: bigint;
        die2: bigint;
    };
} | {
    __kind__: "GameStarted";
    GameStarted: null;
} {
    return "PlayerJoined" in value ? {
        __kind__: "PlayerJoined",
        PlayerJoined: value.PlayerJoined
    } : "GameWon" in value ? {
        __kind__: "GameWon",
        GameWon: value.GameWon
    } : "Bankrupt" in value ? {
        __kind__: "Bankrupt",
        Bankrupt: value.Bankrupt
    } : "Moved" in value ? {
        __kind__: "Moved",
        Moved: value.Moved
    } : "SentToJail" in value ? {
        __kind__: "SentToJail",
        SentToJail: value.SentToJail
    } : "RentPaid" in value ? {
        __kind__: "RentPaid",
        RentPaid: value.RentPaid
    } : "TaxPaid" in value ? {
        __kind__: "TaxPaid",
        TaxPaid: value.TaxPaid
    } : "PropertyBought" in value ? {
        __kind__: "PropertyBought",
        PropertyBought: value.PropertyBought
    } : "Rolled" in value ? {
        __kind__: "Rolled",
        Rolled: value.Rolled
    } : "GameStarted" in value ? {
        __kind__: "GameStarted",
        GameStarted: value.GameStarted
    } : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ICP: null;
} | {
    ckBTC: null;
}): Currency {
    return "ICP" in value ? Currency.ICP : "ckBTC" in value ? Currency.ckBTC : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Lobby: null;
} | {
    Playing: null;
} | {
    Finished: null;
}): GamePhase {
    return "Lobby" in value ? GamePhase.Lobby : "Playing" in value ? GamePhase.Playing : "Finished" in value ? GamePhase.Finished : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Ok: _GameView;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: GameView;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_GameView_n3(_uploadFile, _downloadFile, value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Ok: {
        die1: bigint;
        die2: bigint;
        event: string;
        newPosition: bigint;
    };
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: {
        die1: bigint;
        die2: bigint;
        event: string;
        newPosition: bigint;
    };
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GameView>): Array<GameView> {
    return value.map((x)=>from_candid_GameView_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GameEvent>): Array<GameEvent> {
    return value.map((x)=>from_candid_GameEvent_n7(_uploadFile, _downloadFile, x));
}
function to_candid_CreateGameArgs_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateGameArgs): _CreateGameArgs {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_Currency_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Currency): _Currency {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stakeAmount: bigint;
    currency: Currency;
}): {
    stakeAmount: bigint;
    currency: _Currency;
} {
    return {
        stakeAmount: value.stakeAmount,
        currency: to_candid_Currency_n17(_uploadFile, _downloadFile, value.currency)
    };
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Currency): {
    ICP: null;
} | {
    ckBTC: null;
} {
    return value == Currency.ICP ? {
        ICP: null
    } : value == Currency.ckBTC ? {
        ckBTC: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
